### PR TITLE
FHIR Alignments

### PR DESCRIPTION
**Pull request by markkramerus**
There are quite a few changes because I have renamed some properties in base to align better with FHIR. This will be a process that will take more than just this pull request, but I don't want to let it get too big.

### CODE REVIEW

**Comment by rutemartins** [comment]
Travis is failing

**Comment by mlterryMitre** [comment]
@markkramerus - the Travis error could be related to the shr_brca.txt and the change from `Based on: CodedLaboratoryObservation` to `Based on: TumorMarkerObservation`.

**Comment by markkramerus** [comment]
Closing... going to do another pull soon with updated version.

**Comment by markkramerus** [comment]
Travis failures are all from in es6 exporter. Otherwise the build is clean. I suggest we take this as the new baseline for dev.

**Pull request merged**
