### PR TITLE
Dev r4map mk

### PR DESCRIPTION
**Pull request by markkramerus**
Various updates to align shr classes and datatypes with FHIR R4.

### CODE REVIEW

**Comment by markkramerus** [comment]
Travis might be unable to compile because it is not using 5.18.0 beta 4, which is required.

**Comment by markkramerus** [comment]
Travis is failing because it is not using CLI 5.18.0 beta 4, which is required for R4.

**Comment by cmoesel** [comment]
Hold on 10 minutes and shr-cli master will have all the R4 support.  We can then force travis to run again (I think).

**Comment by cmoesel** [comment]
I reran Travis after merging the R4 support to SHR CLI and now we are passing!

**Comment by cmoesel** [comment]
Good find @mlterryMitre.  I only ran the configs that compile _all_ the DSTU2 or STU3 or R4 definitions.  I did not try the more specific configs.

**Comment by markkramerus** [comment]
Problem was in ig-mcode-cp. We made PanelMembers MS, but PanelMembers wasn't mapped to anything in R4.

**Pull request merged**
