### PR TITLE
Reorganized file structure of SHR repo

### PR DESCRIPTION
**Pull request by markkramerus**
Also renamed files with dashes (-) instead of underscores (_) in file names. It was getting quite confusing to have no convention.  Reorganization will mean a slight change of how we run CLI. The command will have to include the path to the config file, as follows:
`shr-cli-6.5.0> node . ../shr_spec/spec -l error -c ig-sw/ig-sw-config.json`
or 
`shr-cli-6.5.0> node . ../shr_spec/spec -l error -c ig-mcode/ig-mcode-r4-config.json`

Now, if only we could rename the shr_spec (underscore) repo to shr-spec (dash) the world would be in complete harmony...

### CODE REVIEW

**Comment by rutemartins** [comment]
“Thank your for submitting your PR. We’ve noticed you’ve submitted it while on PTOB and that’s strictly prohibited under our enjoying life policy. Please attempt resubmitted when back in the office. We appreciate your commitment.”

**Comment by markkramerus** [comment]
> “Thank your for submitting your PR. We’ve noticed you’ve submitted it while on PTOB and that’s strictly prohibited under our enjoying life policy. Please attempt resubmitted when back in the office. We appreciate your commitment.”

Removing my hands from the keyboard now!

**Comment by markkramerus** [comment]
May, you may need to adjust your command line. I don't know what directory you are in when you issue the CLI command, but this works for me, when I'm in the shr-cli directory:
```
C:\Users\mkramer\Documents\GitHub\shr-cli-6.5.0>node . ../shr_spec/spec -l error -c ig-mcode/ig-mcode-r4-config.json
------------------------------------------------------------
Elapsed time: 102.433s
0 errors
12 warnings (shr-text-input, shr-fhir-export)
------------------------------------------------------------
```

**Comment by rutemartins** [comment]
Worked for me as well for mCODE and sw. I think you need to lose the `./spec/` in your path because you've already pointed to `shr_spec/spec`, so you only need to include the subdirectory. @markkramerus did you test out all the IGs?

**Comment by markkramerus** [comment]
I'm not online, I'm on vacation. Yes, I ran all the IGs.

**Comment by mlterryMitre** [comment]
ok. probably my paths then.  as long as Rute checked, we're good.

**Pull request merged**
