### PR TITLE
Eliminate some unwanted profiles

### PR DESCRIPTION
**Pull request by markkramerus**
1) Made changes so we don't get BC profiles on Patient, Provider, Encounter, and Device.
2) Removed SubjectIfNotPersonOfRecord, SourceOfInformation, Recorded, Signed -- since these were cluttering up all observations
3) Added MTH code for StageSuffix -- not great, but better than nothing if properly documented

### CODE REVIEW

**Comment by rutemartins** [comment]
@markkramerus you want to merge to shimi not master, right?

**Comment by mlterryMitre** [comment]
@markkramerus - I did a merge of your submitted changes to shr_oncology and it's failing the Travis CI build.  Not sure why.  Can you check for me?

**Comment by mlterryMitre** [comment]
Looks like some elements were lost in the merge.  I'll need to revert this commit.

**Comment by rutemartins** [comment]
@mlterryMitre I think you merged in the wrong direction, so all Mark's changes were reverted. You want to revert commit 644f8b3. Not sure how this happened...

**Comment by mlterryMitre** [comment]
Yeh, not sure either.  I just directly clicked on the link on the UI that said "resolve comments" and tried choosing all of the comment blocks marked with "mk".  I'll just work with @markkramerus later today to revert and start fresh before my shr_oncology conflict merge.

**Pull request merged**
