### PR TITLE
Revitalized vitals for mCODE

### PR DESCRIPTION
**Pull request by markkramerus**
Moved from parking lot to spec and updated the ig-mcode-config file to include the three vitals in mCODE.

### CODE REVIEW

**Comment by markkramerus** [comment]
This PR has known errors in ES6 export modules (@cmoesel) is working on a fix. These errors do not affect building the IG.
436 errors (shr-es6-export)

**Comment by markkramerus** [comment]
The Travis failures are in ES-6 export -- so essentially a  pass.

**Comment by mlterryMitre** [comment]
@markkramerus - the generated IG is showing the higher level attributes (HeadlessPanel, CodedLaboratoryObservation, CodedNonLaboratoryObservation, etc) in the generated IG when specifying `ig-mcode-config.json`.  Is this what we want or do we further need to adjust this newer filtering strategy?

**Comment by cmoesel** [comment]
@markkramerus -- I have a partial fix ready.  In short, it makes the error message go away (because I fixed that problem), but it introduces a new problem in the generated ES6 code.  Dylan Hall is taking a look at it.

**Comment by markkramerus** [comment]
> @markkramerus - the generated IG is showing the higher level attributes (HeadlessPanel, CodedLaboratoryObservation, CodedNonLaboratoryObservation, etc) in the generated IG when specifying `ig-mcode-config.json`. Do we want to expose this, or do we further need to adjust this newer filtering strategy?

@mlterryMitre in theory there is nothing wrong with the IG filtering in the config file. We're going to have to engage with Dylan if this keeps happening.

**Pull request merged**
